# AppVeyor CI build file

# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

# version format
version: 2017.0.{build}

shallow_clone: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- dotnet restore -v Minimal

build_script:
- dotnet build */**/project.json --configuration %CONFIGURATION%

after_build:
- dotnet pack "CertiPay.Taxes.Federal" --configuration %CONFIGURATION% -o artifacts

artifacts:
- path: artifacts\**\*.*

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**\bin\$(Configuration)\**\win7-x64\CertiPay.**.Tests.dll'

#---------------------------------#
#       artifacts configuration   #
#---------------------------------#

deploy:
- provider: NuGet
  on: 
    branch: master
  api_key:
    secure: tj8axlUnLaJXMzsVHzNj6dT8VROvH1ChDSv9bKkQG4oNRB/6pI4oefW5WAhuIDIE